import { initializeApp, getApps, getApp } from 'firebase/app';
import {
  getAuth,
  signInWithPopup,
  GoogleAuthProvider,
  onAuthStateChanged,
  User,
  signOut,
} from 'firebase/auth';
import firebaseConfig from '../../firebase-applet-config.json';

// Ensure Firebase is initialized only once
const app = getApps().length > 0 ? getApp() : initializeApp(firebaseConfig);
export const auth = getAuth(app);

const SCOPES = ['https://www.googleapis.com/auth/drive.file'];

const provider = new GoogleAuthProvider();
SCOPES.forEach((scope) => provider.addScope(scope));

let isSigningIn = false;
let cachedAccessToken: string | null = null;
let cachedFolderId: string | null = null;

export const initAuth = (
  onAuthSuccess?: (user: User, token: string) => void,
  onAuthFailure?: () => void
) => {
  return onAuthStateChanged(auth, async (user: User | null) => {
    if (user) {
      if (cachedAccessToken) {
        if (onAuthSuccess) onAuthSuccess(user, cachedAccessToken);
      } else if (!isSigningIn) {
        // If user is logged into Firebase Auth but memory token was cleared on page reload,
        // we can prompt for sign-in or wait for user click
        cachedAccessToken = null;
        if (onAuthFailure) onAuthFailure();
      }
    } else {
      cachedAccessToken = null;
      if (onAuthFailure) onAuthFailure();
    }
  });
};

export const googleSignIn = async (): Promise<{ user: User; accessToken: string } | null> => {
  try {
    isSigningIn = true;
    const result = await signInWithPopup(auth, provider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    if (!credential?.accessToken) {
      throw new Error('Failed to get access token from Google sign in');
    }

    cachedAccessToken = credential.accessToken;
    return { user: result.user, accessToken: cachedAccessToken };
  } catch (error: any) {
    console.error('Sign in error:', error);
    throw error;
  } finally {
    isSigningIn = false;
  }
};

export const getAccessToken = async (): Promise<string | null> => {
  return cachedAccessToken;
};

export const logout = async () => {
  await signOut(auth);
  cachedAccessToken = null;
  cachedFolderId = null;
};

export interface DriveUploadResult {
  id: string;
  name: string;
  webViewLink?: string;
}

/**
 * Finds or creates a dedicated directory in Google Drive: "AudioSpark Podcasts"
 */
export async function getOrCreateDriveFolder(
  folderName: string = 'AudioSpark Podcasts'
): Promise<string | null> {
  if (cachedFolderId) return cachedFolderId;
  const token = await getAccessToken();
  if (!token) return null;

  try {
    // Search for existing folder
    const q = encodeURIComponent(`name = '${folderName}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false`);
    const searchRes = await fetch(`https://www.googleapis.com/drive/v3/files?q=${q}&fields=files(id,name)`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (searchRes.ok) {
      const data = await searchRes.json();
      if (data.files && data.files.length > 0) {
        cachedFolderId = data.files[0].id;
        return cachedFolderId;
      }
    }

    // Create new folder
    const createRes = await fetch('https://www.googleapis.com/drive/v3/files', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: folderName,
        mimeType: 'application/vnd.google-apps.folder',
      }),
    });

    if (createRes.ok) {
      const folderData = await createRes.json();
      cachedFolderId = folderData.id;
      return cachedFolderId;
    }
  } catch (err) {
    console.warn('Could not create or find Drive folder, will upload to root', err);
  }
  return null;
}

/**
 * Uploads a file (Blob / Buffer) directly to Google Drive via multipart upload
 */
export async function uploadBlobToGoogleDrive(options: {
  filename: string;
  blob: Blob;
  mimeType?: string;
  description?: string;
}): Promise<DriveUploadResult> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Please sign in to Google Drive first.');
  }

  const folderId = await getOrCreateDriveFolder();
  const metadata: Record<string, any> = {
    name: options.filename,
    mimeType: options.mimeType || options.blob.type || 'audio/wav',
    description: options.description || 'Generated by AudioSpark AI Studio',
  };

  if (folderId) {
    metadata.parents = [folderId];
  }

  // Multipart body
  const boundary = 'foo_bar_baz_' + Math.random().toString(36).substring(2);
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const metaPart = `Content-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}`;
  const fileHeader = `Content-Type: ${metadata.mimeType}\r\n\r\n`;

  // Construct multipart Blob
  const multipartBlob = new Blob(
    [
      delimiter,
      metaPart,
      delimiter,
      fileHeader,
      options.blob,
      closeDelimiter,
    ],
    { type: `multipart/related; boundary=${boundary}` }
  );

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': `multipart/related; boundary=${boundary}`,
      },
      body: multipartBlob,
    }
  );

  if (!res.ok) {
    const errText = await res.text();
    let errJson: any;
    try {
      errJson = JSON.parse(errText);
    } catch {}
    throw new Error(errJson?.error?.message || `Failed to upload to Google Drive (${res.status})`);
  }

  const data = await res.json();
  return {
    id: data.id,
    name: data.name,
    webViewLink: data.webViewLink,
  };
}

/**
 * Uploads audio from a remote URL or server path directly to Google Drive
 */
export async function uploadUrlToGoogleDrive(options: {
  audioUrl: string;
  filename: string;
  mimeType?: string;
  description?: string;
}): Promise<DriveUploadResult> {
  const res = await fetch(options.audioUrl);
  if (!res.ok) {
    throw new Error(`Failed to retrieve audio data from server: ${res.statusText}`);
  }
  const blob = await res.blob();
  return uploadBlobToGoogleDrive({
    filename: options.filename,
    blob,
    mimeType: options.mimeType || 'audio/wav',
    description: options.description,
  });
}
